name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd client && npm ci

      - name: Build client
        run: npm run build

      - name: Run tests
        run: |
          # Add tests when implemented
          echo "Tests would run here"

      - name: Check for security vulnerabilities
        run: npm audit --audit-level=high